### ISSUE TITLE
Save to String

### ISSUE THREAD

**Issue by henriberisha** [RobTillaart/XMLWriter#13]
I want to congratulate the developer for the outstanding work on this library. 

I am trying to use this library to create an XML and save it into a String. Is this possible with your library? 
If so, please can you provide some guidance? 

Thank you

**Comment by RobTillaart** [comment]
Thanks for this question.
The library cannot save the output directly in a String.
Can you explain why you want to save the XML in a String?
What would you do with the String?

**Comment by RobTillaart** [comment]
@henriberisha 
PR with example created, build is running.
uses my **https://github.com/RobTillaart/PrintString** library

**Comment by RobTillaart** [comment]
Example added in master branch
https://github.com/RobTillaart/XMLWriter/tree/master/examples/XMLWriterString

**Comment by henriberisha** [comment]
Hello Rob, thank you very much for your fast reply. 
I am working on an IoT side project that involves an ESP32. My use case is that i need to build an XML and send it to a MQTT broker as a string.

I was thinking to build the XML straight into a String and publish it like that. 

Thank you so much for your effort and providing the example. Later today i will be able to work on it. 

I appreciate your help and thank you for making this library.

**Comment by RobTillaart** [comment]
you're welcome,
if no questions remain (after testing) you may close the issue.
